version: '3'
services:
  jekyll:
      image: jekyll/jekyll:3.8
      command: jekyll serve
      environment: 
        - JEKYLL_ENV=development
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll
          - ./vendor/bundle:/usr/local/bundle